### ISSUE TITLE
Deployment fails on 2nd deployment due to Prisma migration error

### ISSUE THREAD

**Issue by dchadcluff** [epicweb-dev/epic-stack#598]
I just created a brand new Epic Stack to show someone how it worked. Ran through the setup following the docs and choosing the defaults. Deployed to Fly.io, which worked, and then setup a GitHub repo per the Deployment doc. Pushed the code and get a Prisma migration error.

Verified this by starting a new Epic Stack and doing it again, ensuring no code changes get made and following the instructions in the documentation. It also fails on the 1st push to GitHub (and the 2nd deployment to fly)

```
2024-01-17T03:50:11.294 app[***] den [info] level=INFO msg="executing command: npx [prisma migrate deploy]"

2024-01-17T03:50:13.191 app[***] den [info] Prisma schema loaded from prisma/schema.prisma

2024-01-17T03:50:13.209 app[***] den [info] Datasource "db": SQLite database "sqlite.db" at "file:/litefs/data/sqlite.db"

2024-01-17T03:50:13.358 app[***] den [info] 1 migration found in prisma/migrations

2024-01-17T03:50:13.376 app[***] den [info] Error: P3009

2024-01-17T03:50:13.376 app[***] den [info] migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

2024-01-17T03:50:13.376 app[***] den [info] The `20230914194400_init` migration started at 2024-01-17 03:29:22.043 UTC failed
```

Is there potentially some secret that's not getting set in Fly for the database location?

**Comment by kentcdodds** [comment]
It should be noted that the Epic Stack template project is working fine, so there's probably something funny going on with a new project.

**Comment by johntheo** [comment]
Same issue with me! 
Failed in both machines: stagging and prod one.

I found this article here and was about to try:
https://community.fly.io/t/issues-with-prisma-migrations/17045

@kentcdodds If I fork the Epic Stack template and create my project from there, is it supposed to work?

**Comment by kentcdodds** [comment]
Forking it shouldn't make any difference with the migration. Also, I'm not sure this is related because we didn't make any changes to the migration.

**Comment by kentcdodds** [comment]
What I find is interesting is that the error says:

> 2024-01-17T19:09:33Z app[4d891263c73228] sjc [info]The `20230914194400_init` migration started at 2024-01-17 19:04:25.974 UTC failed

But if you look at the previous logs it says that migration was successful. This seems like a prisma issue to me. But I'm not sure what's going on.

```
2024-01-17T19:04:25Z app[4d891263c73228] sjc [info]Prisma schema loaded from prisma/schema.prisma
2024-01-17T19:04:25Z app[4d891263c73228] sjc [info]Datasource "db": SQLite database "sqlite.db" at "file:/litefs/data/sqlite.db"
2024-01-17T19:04:25Z app[4d891263c73228] sjc [info]1 migration found in prisma/migrations
2024-01-17T19:04:25Z app[4d891263c73228] sjc [info]Applying migration `20230914194400_init`
2024-01-17T19:04:26Z app[4d891263c73228] sjc [info]The following migration have been applied:
2024-01-17T19:04:26Z app[4d891263c73228] sjc [info]migrations/
2024-01-17T19:04:26Z app[4d891263c73228] sjc [info]  └─ 20230914194400_init/
2024-01-17T19:04:26Z app[4d891263c73228] sjc [info]    └─ migration.sql
2024-01-17T19:04:26Z app[4d891263c73228] sjc [info]All migrations have been successfully applied.
```

**Comment by kentcdodds** [comment]
Perhaps is a bug in the latest prisma. So I've updated all deps and we'll see if the Epic Stack deploy fails: https://github.com/epicweb-dev/epic-stack/commit/97d789f737380be318f57425be9040ce360b12ce

**Comment by kentcdodds** [comment]
That deploy worked ok. So it's unlikely to be a Prisma regression. But there's definitely something going wrong here. I'm afraid I don't have the resources to look into this right now so any help from anyone else is welcome.

**Comment by shortjared** [comment]
I did a bit of digging. 

Looking at the sqlite database generated on fly.io, the `_prisma_migrations` does not have a `finished_at` value for the `20230914194400_init` migration, as well as having an `applied_steps_count` of `0`.

In a succesful dev migration copy of the database, these are the `finished_at` timestamp and `1` respectively.

Still not sure _why_ this happening. Especially with Prisma claiming successful migration on the initial push. Even more odd, it seems that none of the tables actually exist in the fly.io db until after something in the app uses them.

**Comment by weco-dev** [comment]
Same issue here
Following

**Comment by kentcdodds** [comment]
Ok, @benbjohnson investigated and open an issue on LiteFS: https://github.com/superfly/litefs/issues/425

A fix is to just do migrations before setting up WAL. https://github.com/epicweb-dev/epic-stack/commit/d1947590d2c4604b12c4b83d29fc02e6cd30a4de

I haven't confirmed this solves the problem myself, so if someone else would like to do that, I would appreciate it!

**Comment by weco-dev** [comment]
@kentcdodds later in the day I'll make a test with the @latest and let you know.

In the meantime, trying to apply your patch didn't work as expected

```
 2024/01/19 07:45:53 listening on [fdaa:5:7167:a7b:251:a1b3:54e6:2]:22 (DNS: [fdaa::3]:53)
  node:internal/modules/esm/get_format:160
    throw new ERR_UNKNOWN_FILE_EXTENSION(ext, filepath);
          ^
  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".sh" for /myapp/other/start.sh
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
      at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
      at defaultLoad (node:internal/modules/esm/load:143:22)
      at async ModuleLoader.load (node:internal/modules/esm/loader:409:7)
      at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:45)
      at async link (node:internal/modules/esm/module_job:76:21) {
    code: 'ERR_UNKNOWN_FILE_EXTENSION'
  }
```

I'm gonna investigate also on this later on.
Thanks for time and support, it really helps

**Comment by weco-dev** [comment]
Temporary solved issue on .sh extension making a `start.js` file.

```
import { execSync } from 'child_process'

execSync("node ./other/setup-swap.js")
execSync("sqlite3 $DATABASE_PATH 'PRAGMA journal_mode = WAL;'")
execSync("sqlite3 $CACHE_DATABASE_PATH 'PRAGMA journal_mode = WAL;'")
execSync("npx prisma migrate deploy")
execSync("npm start")
```

Still, having some troubles finding the DB.
```
   INFO Starting init (commit: 8995e367)...
   INFO Mounting /dev/vdb at /data w/ uid: 0, gid: 0 and chmod 0755
   INFO Resized /data to 1056964608 bytes
   INFO Preparing to run: `docker-entrypoint.sh ./other/start.js` as root
   INFO [fly api proxy] listening at /.fly/api
  2024/01/19 08:12:37 listening on [fdaa:5:7167:a7b:251:a1b3:54e6:2]:22 (DNS: [fdaa::3]:53)
  Error: unable to open database "/data/not-actually-litefs/data/sqlite.db": unable to open database file
  node:internal/errors:932
    const err = new Error(message);
                ^
  Error: Command failed: sqlite3 $DATABASE_PATH 'PRAGMA journal_mode = WAL;'
  Error: unable to open database "/data/not-actually-litefs/data/sqlite.db": unable to open database file
      at checkExecSyncError (node:child_process:890:11)
      at execSync (node:child_process:962:15)
      at file:///myapp/other/start.js:4:1
      at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
      at async loadESM (node:internal/process/esm_loader:28:7)
      at async handleMainPromise (node:internal/modules/run_main:113:12) {
```

In a couple of hours I'll continue the debug with @latest

**Comment by Yonatani** [comment]
Hey guys, for some reason this issue is closed, im also having these errors in the past few days (tried to open several projects), trying to figure out whats wrong, will follow this topic as well 🙏

**Comment by weco-dev** [comment]
@kentcdodds the fix to do migrations before setting up WAL worked.
I deployed for the second time on a new app created with `epic-stack@latest` and worked well.

**Comment by dchadcluff** [comment]
Applied the fix and it worked for me as well. I was able to submit several commits with successful deployments. And then I tried to modify the prisma schema and generate a new migration file. I end up getting the same error as before, failed migration. P3009

```
2024-01-22T03:03:02.731 app[3d8d111a537389] den [info] Prisma schema loaded from prisma/schema.prisma

2024-01-22T03:03:02.755 app[3d8d111a537389] den [info] Datasource "db": SQLite database "sqlite.db" at "file:/litefs/data/sqlite.db"

2024-01-22T03:03:02.841 app[3d8d111a537389] den [info] 2 migrations found in prisma/migrations

2024-01-22T03:03:02.852 app[3d8d111a537389] den [info] Error: P3009

2024-01-22T03:03:02.852 app[3d8d111a537389] den [info] migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
```

**Comment by paolotiu** [comment]
For those following this is now fixed on  [v.0.5.11](https://github.com/superfly/litefs/releases/tag/v0.5.11) with the pr https://github.com/superfly/litefs/pull/426

**Comment by kentcdodds** [comment]
Can someone confirm this actually fixes the issue of using WAL mode? I was under the impression that this doesn't fix WAL mode and instead just improves the error message, but I could be reading this wrong...

**Comment by benbjohnson** [comment]
@kentcdodds The change prevents WAL mode writes from being used with exclusive locking mode which will show as an error in the LiteFS logs. I posted an issue against the `prisma-engines` repository to see if they'd consider removing exclusive locking mode or making it optional. https://github.com/prisma/prisma-engines/issues/4675

**Comment by kentcdodds** [comment]
Good issue to up-vote everyone! Thanks Ben!

**Comment by kennymcginnis** [comment]
Can I still make comments on a Closed issue?
I cannot deploy to fly - I have deployed once, but I am unable to redeploy a second time.

I have tried to move `npx prisma migrate deploy` before the WAL in my `litefs.yml`
I have also tried updating flyio `flyio/litefs:0.5.11` in my `Dockerfile`

Here is the error that I see...

```
 => [internal] load build definition from Dockerfile                                                                                                                                                                           0.3s
 => => transferring dockerfile: 2.17kB                                                                                                                                                                                         0.3s 
 => [internal] load .dockerignore                                                                                                                                                                                              0.2s 
 => => transferring context: 35B                                                                                                                                                                                               0.2s 
 => [internal] load metadata for docker.io/library/node:20-bookworm-slim                                                                                                                                                       0.4s
 => FROM docker.io/flyio/litefs:0.5.11                                                                                                                                                                                         0.1s
 => => resolve docker.io/flyio/litefs:0.5.11                                                                                                                                                                                   0.1s 
 => [base 1/2] FROM docker.io/library/node:20-bookworm-slim@sha256:b54988ddece70caaeb64f8952212bbbb3026ed58e5308f421fbee60a90717a74                                                                                            0.0s 
 => [internal] load build context                                                                                                                                                                                              0.9s 
 => => transferring context: 103.74kB                                                                                                                                                                                          0.9s 
 => CACHED [base 2/2] RUN apt-get update && apt-get install -y fuse3 openssl sqlite3 ca-certificates                                                                                                                           0.0s 
 => CACHED [stage-4  1/14] RUN echo "#!/bin/sh\nset -x\nsqlite3 $DATABASE_URL" > /usr/local/bin/database-cli && chmod +x /usr/local/bin/database-cli                                                                           0.0s 
 => CACHED [stage-4  2/14] WORKDIR /myapp                                                                                                                                                                                      0.0s 
 => CACHED [build 1/6] WORKDIR /myapp                                                                                                                                                                                          0.0s
 => [deps 2/3] ADD package.json package-lock.json .npmrc ./                                                                                                                                                                    0.0s 
 => [deps 3/3] RUN npm install --include=dev                                                                                                                                                                                  43.3s 
 => CACHED [build 2/6] COPY --from=deps /myapp/node_modules /myapp/node_modules                                                                                                                                                0.0s
 => [production-deps 3/4] ADD package.json package-lock.json .npmrc ./                                                                                                                                                         0.5s
 => [build 3/6] ADD prisma .                                                                                                                                                                                                   1.7s
 => CANCELED [production-deps 4/4] RUN npm prune --omit=dev                                                                                                                                                                    5.6s
 => ERROR [build 4/6] RUN npx prisma generate                                                                                                                                                                                  4.4s
------
 > [build 4/6] RUN npx prisma generate:
#0 1.528 Prisma schema loaded from schema.prisma
#0 4.276 Error:
#0 4.276 ✔ Generated Prisma Client (v5.8.1) to ./node_modules/@prisma/client in 408ms
#0 4.276
#0 4.276 Command failed: "/myapp/node_modules/.bin/mmdc" -i "/tmp/prisma-erd-NRnimi/prisma.mmd" -o "/myapp/ERD.svg" -c "/tmp/prisma-erd-NRnimi/config.json" -p "/tmp/prisma-erd-NRnimi/puppeteerConfig.json"
#0 4.276
#0 4.276
#0 4.308 npm notice
#0 4.308 npm notice New minor version of npm available! 10.2.4 -> 10.4.0
#0 4.308 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
#0 4.309 npm notice Run `npm install -g npm@10.4.0` to update!
#0 4.310 npm notice
------
Error: failed to fetch an image or build from source: error building: failed to solve: executor failed running [/bin/sh -c npx prisma generate]: exit code: 1
```

**Comment by kentcdodds** [comment]
Based on the error it looks like it's completely unrelated to anything in the Epic Stack. My guess is it's something wrong with this package that I'm guessing you added: https://www.npmjs.com/package/prisma-erd-generator

You'll have to try and understand the requirements for that package and make sure you update your dockerfile to satisfy those system requirements.

Or just remove the package because it looks like it's only necessary for development.

**Comment by kennymcginnis** [comment]
Thanks so much, @kentcdodds! And thanks for the quick response!
I did not connect the dots between `-erd-` and the error message!
I removed the package and was able to progress (finally)! phew!
